/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YbcSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface YbcTooltip {
        "open": boolean;
        "tooltip": string;
    }
}
declare global {
    interface HTMLYbcSideDrawerElement extends Components.YbcSideDrawer, HTMLStencilElement {
    }
    var HTMLYbcSideDrawerElement: {
        prototype: HTMLYbcSideDrawerElement;
        new (): HTMLYbcSideDrawerElement;
    };
    interface HTMLYbcTooltipElement extends Components.YbcTooltip, HTMLStencilElement {
    }
    var HTMLYbcTooltipElement: {
        prototype: HTMLYbcTooltipElement;
        new (): HTMLYbcTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ybc-side-drawer": HTMLYbcSideDrawerElement;
        "ybc-tooltip": HTMLYbcTooltipElement;
    }
}
declare namespace LocalJSX {
    interface YbcSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface YbcTooltip {
        "open"?: boolean;
        "tooltip"?: string;
    }
    interface IntrinsicElements {
        "ybc-side-drawer": YbcSideDrawer;
        "ybc-tooltip": YbcTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ybc-side-drawer": LocalJSX.YbcSideDrawer & JSXBase.HTMLAttributes<HTMLYbcSideDrawerElement>;
            "ybc-tooltip": LocalJSX.YbcTooltip & JSXBase.HTMLAttributes<HTMLYbcTooltipElement>;
        }
    }
}
